secrets:
  webhookEndpoint: ""
  apiKey: "change-me"

spring:
  data:
    mongodb:
      # Mongo server host.
      host: localhost
      # Mongo server port.
      port: 27017
      # Login user of the mongo server.
      # username:
      # Login password of the mongo server.
      # password:
      # Database name.
      database: airdata
      # Mongo database URI. When set, host and port are ignored.
      # uri:
      # Authentication database name.
      # authentication-database:
      # Fully qualified name of the FieldNamingStrategy to use.
      # field-naming-strategy:
      # GridFS database name.
      # grid-fs-database:
      repositories:
        # Enable Mongo repositories.
        enabled: true
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

server:
  tomcat:
    max-allow-size: 300MB
