changeable:
  multiplierTime: 122
  restUrl: "http://api.luftdaten.info/static/v1/filter/type=SDS011"
  restUrlHamburg: "http://api.luftdaten.info/static/v1/filter/type=SDS011&country=DE&area=53.33,10.0,10"
